### PR TITLE
Update system tests to run on simulator and in github workflow

### PR DESCRIPTION
**Pull request by kingst**

### CODE REVIEW

**Review by jaimejiyepark — COMMENTED** [review]
is it possible to sublclass scanbase and add the fake loops instead of modifying it?

**Comment by kingst** [comment]
I couldn't find a way to do that. This loop is protected with both a `testDataSource` and `isSimulator` check so it should be safe, but please do double check that because I agree with your concern

**Comment by jaimejiyepark** [comment]
Tested the system tests out with the simulator and they work. Just to be safe, should we add the `internal` attribute to those functions since they should only be used internally?

**Comment by jaimejiyepark** [comment]
i'll test it once more with the changes

**Review by jaimejiyepark — APPROVED** [review]

**Pull request merged**
