### PR TITLE
return normlized co-ordinates from SSD

### PR DESCRIPTION
**Pull request by dxaen**

### CODE REVIEW

**Comment by kingst** [comment]
To keep debugging easy I suggest keeping the rect in image coordinates but convert only the dict to a normalized value

**Comment by dxaen** [comment]
Good point. Let me make the change.

**Comment by dxaen** [comment]
https://github.com/getbouncer/cardscan-ios/pull/68/commits/a58e479b485b3bc5caf40e1781e6b6f915497b20

**Comment by kingst** [comment]
#shipit. Eventually it'd be nice to have toDict(normalized: CGSize) as an extension to CGRect, but for now let's ship this as is.

**Pull request merged**
